---
# tasks file for environment
- name: save variable settings in /etc/profile.d/custom.sh
  lineinfile:
    path: /etc/profile.d/custom.sh
    regexp: '^{{ item.key }}='
    line: '{{ item.key }}="{{ item.value }}"'
    create: yes
    mode: "0644"
  loop: "{{ environment_list | dict2items }}"
